version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: clean
          command: rm -f lib/opentmi-client.js lib/opentmi-client.min.js
      - run:
          name: lint
          command: npm run lint
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: tap npm test
      - run:
          name: doc
          command: npm run doc
      - store_artifacts:
          path: doc
          prefix: documentations
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: coverage/coverage.json