version: 2

workflows:
  version: 2
  test-publish:
    jobs:
      - test-node6:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - test-node8:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - test-node-latest:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - publish:
          requires:
            - test-node6
            - test-node8
            - test-node-latest
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/


defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:6.11.4-browsers
      environment:
       CHROME_BIN: "/usr/bin/google-chrome"
  steps:
    - checkout
    - run: node --version > _tmp_file
    - restore_cache:
        key: dependency-cache-{{ checksum "_tmp_file" }}-{{ checksum "package-lock.json" }}
    - run:
        name: versions
        command: |
          npmv=$(echo $(npm -v) | head -c 1); if [ "$npmv" -lt "6" ]; then sudo npm i -g npm@latest; else echo "Node.js Docker Team finally decided to include npm v6+ in latest image; you can remove this script now"; fi
          node --version
          npm --version
    - run:
        name: install-npm
        command: npm ci
    - save_cache:
        key: dependency-cache-{{ checksum "_tmp_file" }}-{{ checksum "package-lock.json" }}
        paths:
          - ./node_modules
    - run:
        name: clean
        command: rm -f lib/opentmi-client.js lib/opentmi-client.min.js
    - run:
        name: build
        command: npm run build
    - run:
        name: test-node
        command: npm run coverage
        environment:
          REPORTER: mocha-circleci-reporter
          MOCHA_FILE: junit/test-results.xml
    - run:
        name: coveralls
        command: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    - run:
        name: test-browser
        command: npm run test-browser
    - run:
        name: lint
        command: npm run lint
        when: always
    - run:
        name: doc
        command: npm run doc
    - store_test_results:
        path: junit
    - store_artifacts:
        path: junit
    - store_artifacts:
        path: docs
        prefix: documentations
    - store_artifacts:
        path: coverage
        prefix: coverage
    - store_test_results:
        path: coverage/coverage.json
jobs:
  test-node6:
    <<: *defaults
    docker:
    - image: circleci/node:6.11.4-browsers
      environment:
       CHROME_BIN: "/usr/bin/google-chrome"
  test-node8:
    <<: *defaults
    docker:
    - image: circleci/node:8.11.1-browsers
      environment:
       CHROME_BIN: "/usr/bin/google-chrome"
  test-node-latest:
    <<: *defaults
    docker:
    - image: circleci/node:latest-browsers
      environment:
       CHROME_BIN: "/usr/bin/google-chrome"
  publish:
    <<: *defaults
    steps:
      - checkout
      - run: node --version > _tmp_file
      - restore_cache:
          key: dependency-cache-{{ checksum "_tmp_file" }}-{{ checksum "package-lock.json" }}
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

